#!/bin/bash

DIR=$HOME/Pictures/Walls
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

swww img ${DIR}/${RANDOMPICS} --resize fit --transition-fps 60 --transition-type grow --transition-pos "$(hyprctl cursorpos)" --invert-y --transition-duration 2
wal -i ${DIR}/${RANDOMPICS}

echo "Successfully set a new wallpaper and generated colors from it."

#pywalfox update
#pywal-discord -t default
#wal-telegram --wal

. $HOME/.config/mako/update-colors.sh &
. $HOME/.config/cava/scripts/update-colors.sh &

cp -r $HOME/.cache/wal/colors-waybar.css $HOME/.config/waybar &
killall -SIGUSR2 waybar